id: I313B52E4
default_language: es
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:31:15.157317
last_modified: 2023-01-04 11:31:15.157324
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  9C6C:
    title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
      Rinpoche
    base_file: 9C6C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
